services:

  frontend:
    build:
      context: ./eco-go
      dockerfile: frontend.Dockerfile
    container_name: mvp-eco-go
    restart: unless-stopped
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    ports:
      - "8082:8082"
      - "19003:19003"
      - "19004:19004"
      - "19005:19005"
    volumes:
      - ./eco-go:/app
      - /app/node_modules
    stdin_open: true
    tty: true